# Generated by Django 4.0.5 on 2022-06-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_fare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='fare',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
